### ISSUE TITLE
Bad namespace name

### ISSUE THREAD

**Issue by md2perpe** [yossi-eynav/pull-requester#1]
You shouldn't use the namespace 'extension' for the commands used by your extension. It is too generic. Instead use 'pull-requester', 'pullRequester' or perhaps even better: 'yossi-eynav.pull-requester'.

Example of use of this namespace:
https://github.com/yossi-eynav/pull-requester/blob/7a18eb5f3468cd96e1b987210eb77f51f482083e/src/extension.ts#L25

**Comment by yossi-eynav** [comment]
@md2perpe  thanks!
I just opened it couple of days ago, changed  the namepsace yesterday.
