### ISSUE TITLE
Storing github token requires elevated rights

### ISSUE THREAD

**Issue by shlomiuziel** [yossi-eynav/pull-requester#4]
In order to store the token in vscode under Windows, vscode must be running with Administrator privileges. That's because the .githubtoken file is stored within vscode folder (under Program Files).
Also, it is nested under an "undefined" folder, would be better if it had a defined name.

**Comment by yossi-eynav** [comment]
Sorry can you explain further? @shlomiuziel

**Comment by shlomiuziel** [comment]
Sure, process.env.HOME is not supported in Windows (so the path resolved within Program Files folder, which requires elevated rights to write to)
Please see https://stackoverflow.com/questions/9080085/node-js-find-home-directory-in-platform-agnostic-way

I submitted a PR to fix this issue.

**Comment by yossi-eynav** [comment]
Amazing, thanks! @shlomiuziel
